Flowpack:
  JsonApi:
    endpoints:
      'testing':
        baseUrl: 'testing'
        version: 'v1'
        resources:
          'entities':
            adapter: 'Flowpack\JsonApi\Tests\Functional\Fixtures\Entities\Adapter'
            entity: 'Neos\Flow\Tests\Functional\Persistence\Fixtures\TestEntity'
            schema: 'Flowpack\JsonApi\Tests\Functional\Fixtures\Entities\Schema'
            allowedMethods:
            - 'list'
            - 'read'
            - 'create'
            - 'update'
            - 'delete'
            related: []
          'restricted-entities':
            adapter: 'Flowpack\JsonApi\Tests\Functional\Fixtures\Entities\Adapter'
            entity: 'Neos\Flow\Tests\Functional\Persistence\Fixtures\TestEntity'
            schema: 'Flowpack\JsonApi\Tests\Functional\Fixtures\Entities\Schema'
            related: []
            allowedMethods: []
          'entity-relations':
            adapter: 'Flowpack\JsonApi\Tests\Functional\Fixtures\RelatedEntities\Adapter'
            entity: 'Neos\Flow\Tests\Functional\Persistence\Fixtures\TestEntity'
            schema: 'Flowpack\JsonApi\Tests\Functional\Fixtures\RelatedEntities\Schema'
            allowedMethods:
            - 'list'
            - 'read'
            - 'create'
            - 'update'
            - 'delete'
            related:
              'entities':
                'Neos\Flow\Tests\Functional\Persistence\Fixtures\TestEntity': 'Flowpack\JsonApi\Tests\Functional\Fixtures\Entities\Schema'
              'subentities':
                'Neos\Flow\Tests\Functional\Persistence\Fixtures\TestEntity': 'Flowpack\JsonApi\Tests\Functional\Fixtures\Entities\Schema'
          'resources':
            adapter: 'Flowpack\JsonApi\JsonApi\PersistentResource\Adapter'
            schema: 'Flowpack\JsonApi\JsonApi\PersistentResource\Schema'
            entity: 'Neos\Flow\ResourceManagement\PersistentResource'
            allowedMethods:
            - 'list'
            - 'read'
            - 'delete'
            related: []
