Ttree:
  JsonApi:
    endpoints:
      'testing':
        baseUrl: 'testing'
        version: 'v1'
        resources:
          'entities':
            adapter: 'Ttree\JsonApi\Tests\Functional\Fixtures\Entities\Adapter'
            entity: 'Neos\Flow\Tests\Functional\Persistence\Fixtures\TestEntity'
            schema: 'Ttree\JsonApi\Tests\Functional\Fixtures\Entities\Schema'
            allowedMethods: ['GET', 'POST', 'UPDATE', 'PATCH', 'DELETE']
            related: []
          'restricted-entities':
            adapter: 'Ttree\JsonApi\Tests\Functional\Fixtures\Entities\Adapter'
            entity: 'Neos\Flow\Tests\Functional\Persistence\Fixtures\TestEntity'
            schema: 'Ttree\JsonApi\Tests\Functional\Fixtures\Schema'
            related: []
            allowedMethods: []
          'entity-relations':
            adapter: 'Ttree\JsonApi\Tests\Functional\Fixtures\RelatedEntities\Adapter'
            entity: 'Neos\Flow\Tests\Functional\Persistence\Fixtures\TestEntity'
            schema: 'Ttree\JsonApi\Tests\Functional\Fixtures\RelatedEntities\Schema'
            allowedMethods: ['GET', 'POST', 'UPDATE', 'PATCH', 'DELETE']
            related:
              'entities':
                'Neos\Flow\Tests\Functional\Persistence\Fixtures\TestEntity': 'Ttree\JsonApi\Tests\Functional\Fixtures\Entities\Schema'
              'subentities':
                'Neos\Flow\Tests\Functional\Persistence\Fixtures\TestEntity': 'Ttree\JsonApi\Tests\Functional\Fixtures\Entities\Schema'
          'resources':
            adapter: 'Ttree\JsonApi\JsonApi\PersistentResource\Adapter'
            schema: 'Ttree\JsonApi\JsonApi\PersistentResource\Schema'
            entity: 'Neos\Flow\ResourceManagement\PersistentResource'
            allowedMethods: ['GET', 'DELETE', 'OPTIONS']
            related: []