- name: 'Resource(s)'
  uriPattern: '{@endpoint}/{@version}/{@resource}(/{identifier})'
  defaults:
    '@package':    'Flowpack.JsonApi'
    '@controller': 'JsonApi'
    '@action':     'index'
    '@format':     'json'
    'identifier':  ''
  httpMethods: ['GET', 'POST', 'PATCH', 'UPDATE', 'DELETE', 'OPTIONS']
  appendExceedingArguments: TRUE
  routeParts:
    '@endpoint':
      handler: 'Flowpack\JsonApi\Mvc\Routing\EndpointRoutePartHandler'
    '@version':
      handler: 'Flowpack\JsonApi\Mvc\Routing\VersionRoutePartHandler'
    '@resource':
      handler: 'Flowpack\JsonApi\Mvc\Routing\ResourceRoutePartHandler'

- name: 'Related'
  uriPattern: '{@endpoint}/{@version}/{@resource}/{identifier}/{relationship}'
  defaults:
    '@package':    'Flowpack.JsonApi'
    '@controller': 'JsonApi'
    '@action':     'index'
    '@format':     'json'
  httpMethods: ['GET', 'OPTIONS']
  appendExceedingArguments: TRUE
  routeParts:
    '@endpoint':
      handler: 'Flowpack\JsonApi\Mvc\Routing\EndpointRoutePartHandler'
    '@version':
      handler: 'Flowpack\JsonApi\Mvc\Routing\VersionRoutePartHandler'
    '@resource':
      handler: 'Flowpack\JsonApi\Mvc\Routing\ResourceRoutePartHandler'

- name: 'Self'
  uriPattern: '{@endpoint}/{@version}/{@resource}/{identifier}/relationships/{relationship}'
  defaults:
    '@package': 'Flowpack.JsonApi'
    '@controller': 'JsonApi'
    '@action':     'index'
    '@format':     'json'
  httpMethods: ['GET', 'OPTIONS']
  appendExceedingArguments: TRUE
  routeParts:
    '@endpoint':
      handler: 'Flowpack\JsonApi\Mvc\Routing\EndpointRoutePartHandler'
    '@version':
      handler: 'Flowpack\JsonApi\Mvc\Routing\VersionRoutePartHandler'
    '@resource':
      handler: 'Flowpack\JsonApi\Mvc\Routing\ResourceRoutePartHandler'